window.GAME_LIST = [
  { file: "1.12.html", title: "1.12" },
  { file: "1.5.html", title: "1.5" },
  { file: "1.8.html", title: "1.8" },
  { file: "10minutestilldawn.html", title: "10 Minutes Till Dawn" },
  { file: "12minibattles.html", title: "12 Mini Battles" },
  { file: "1on1soccer.html", title: "1v1 Soccer" },
  { file: "1on1tennis.html", title: "1v1 Tennis" },
  { file: "1v1.lol.html", title: "1v1.lol" },
  { file: "2048.html", title: "2048" },
  { file: "2048cupcakes.html", title: "2048 Cupcakes" },
  { file: "3Dflightsimulator.html", title: "3D Flight Simulator" },
  { file: "8ballclassic.html", title: "8 Ball Classic" },
  { file: "agariolite.html", title: "Agar.io Lite" },
  { file: "ageofwar.html", title: "Age of War" },
  { file: "ageofwar2.html", title: "Age of War 2" },
  { file: "agesofconflict.html", title: "Ages of Conflict" },
  { file: "amongus.html", title: "Among Us" },
  { file: "angrybirds.html", title: "Angry Birds" },
  { file: "angrybirdsshowdown.html", title: "Angry Birds Showdown" },
  { file: "angrybirdsspace.html", title: "Angry Birds Space" },
  { file: "awesometanks.html", title: "Awesome Tanks" },
  { file: "awesometanks2.html", title: "Awesome Tanks 2" },
  { file: "backrooms.html", title: "Backrooms" },
  { file: "badicecream.html", title: "Bad Ice Cream" },
  { file: "badicecream2.html", title: "Bad Ice Cream 2" },
  { file: "badicecream3.html", title: "Bad Ice Cream 3" },
  { file: "baldisbasics.html", title: "Baldi's Basics" },
  { file: "basketballlegends.html", title: "Basketball Legends" },
  { file: "basketballstars.html", title: "Basketball Stars" },
  { file: "bitlife.html", title: "BitLife" },
  { file: "blockysnakes.html", title: "Blocky Snakes" },
  { file: "bloonsTD.html", title: "Bloons TD" },
  { file: "bloonsTD2.html", title: "Bloons TD 2" },
  { file: "bloonsTD3.html", title: "Bloons TD 3" },
  { file: "bloonsTD4.html", title: "Bloons TD 4" },
  { file: "bloonsTD5.html", title: "Bloons TD 5" },
  { file: "bloxorz.html", title: "Bloxorz" },
  { file: "bobtherobber.html", title: "Bob The Robber" },
  { file: "bobtherobber2.html", title: "Bob The Robber 2" },
  { file: "bobtherobber5.html", title: "Bob The Robber 5" },
  { file: "bowmasters.html", title: "Bowmasters" },
  { file: "bubbleshooter.html", title: "Bubble Shooter" },
  { file: "candycrush.html", title: "Candy Crush" },
  { file: "capybaraclicker.html", title: "Capybara Clicker" },
  { file: "chess.html", title: "Chess" },
  { file: "circloO.html", title: "CircloO" },
  { file: "circloO2.html", title: "CircloO 2" },
  { file: "clashofvikings.html", title: "Clash of Vikings" },
  { file: "cleanupio.html", title: "CleanUp.io" },
  { file: "cookieclicker.htm", title: "Cookie Clicker" },
  { file: "crossyroad.htm", title: "Crossy Road" },
  { file: "cuttherope.html", title: "Cut The Rope" },
  { file: "dadish.html", title: "Dadish" },
  { file: "dadish2.html", title: "Dadish 2" },
  { file: "dadish3.html", title: "Dadish 3" },
  { file: "doodlejump.html", title: "Doodle Jump" },
  { file: "driftboss.htm", title: "Drift Boss" },
  { file: "drifthunters.html", title: "Drift Hunters" },
  { file: "drivemad.htm", title: "Drive Mad" },
  { file: "ducklife.html", title: "Duck Life" },
  { file: "ducklife2.html", title: "Duck Life 2" },
  { file: "ducklife3.html", title: "Duck Life 3" },
  { file: "ducklife4.html", title: "Duck Life 4" },
  { file: "ducklife5.html", title: "Duck Life 5" },
  { file: "earntodie.html", title: "Earn To Die" },
  { file: "earntodie2.html", title: "Earn To Die 2" },
  { file: "escaperoad.html", title: "Escape Road" },
  { file: "escaperoad2.html", title: "Escape Road 2" },
  { file: "fnaf.html", title: "FNAF" },
  { file: "fnaf2.html", title: "FNAF 2" },
  { file: "fnaf3.html", title: "FNAF 3" },
  { file: "fnaf4.html", title: "FNAF 4" },
  { file: "footballbros.html", title: "Football Bros" },
  { file: "footballlegends.html", title: "Football Legends" },
  { file: "fruitninja.html", title: "Fruit Ninja" },
  { file: "geometrydash.html", title: "Geometry Dash" },
  { file: "geometrydashlite.html", title: "Geometry Dash Lite" },
  { file: "granny.html", title: "Granny" },
  { file: "granny2.html", title: "Granny 2" },
  { file: "happywheels.html", title: "Happy Wheels" },
  { file: "helixjump.html", title: "Helix Jump" },
  { file: "idlebreakout.html", title: "Idle Breakout" },
  { file: "jetpackjoyride.html", title: "Jetpack Joyride" },
  { file: "learntofly.html", title: "Learn To Fly" },
  { file: "learntofly2.html", title: "Learn To Fly 2" },
  { file: "learntofly3.html", title: "Learn To Fly 3" },
  { file: "minesweeper.html", title: "Minesweeper" },
  { file: "melonplayground.html", title: "Melon Playground" },
  { file: "motox3m.htm", title: "Moto X3M" },
  { file: "motox3m2.html", title: "Moto X3M 2" },
  { file: "motox3m3.html", title: "Moto X3M 3" },
  { file: "pacman.html", title: "Pac-Man" },
  { file: "paperio2.htm", title: "Paper.io 2" },
  { file: "plantsvszombies.html", title: "Plants vs Zombies" },
  { file: "pou.html", title: "Pou" },
  { file: "retrobowl.html", title: "Retro Bowl" },
  { file: "slope.html", title: "Slope" },
  { file: "run.html", title: "Run" },
  { file: "run2.html", title: "Run 2" },
  { file: "run3.html", title: "Run 3" },
  { file: "subwaysurfersbeijing.html", title: "Subway Surfers Beijing" },
  { file: "subwaysurfershavana.html", title: "Subway Surfers Havana" },
  { file: "subwaysurferssanfrancisco.html", title: "Subway Surfers San Francisco" }
];
