window.GAME_LIST = [
  { file: "1.12.html", title: "1.12" },
  { file: "1.5.html", title: "1.5" },
  { file: "1.8.html", title: "1.8" },
  { file: "10minutestilldawn.html", title: "10 Minutes Till Dawn" },
  { file: "12minibattles.html", title: "12 Mini Battles" },
  { file: "1on1soccer.html", title: "1 on 1 Soccer" },
  { file: "1on1tennis.html", title: "1 on 1 Tennis" },
  { file: "1v1.lol.html", title: "1v1.lol" },
  { file: "2048.html", title: "2048" },
  { file: "2048cupcakes.html", title: "2048 Cupcakes" },
  { file: "3Dflightsimulator.html", title: "3D Flight Simulator" },
  { file: "8ballclassic.html", title: "8 Ball Classic" },
  { file: "Alpha_1.2.6.html", title: "Alpha 1.2.6" },
  { file: "Beta_1.3.html", title: "Beta 1.3" },
  { file: "agariolite.html", title: "Agar.io Lite" },
  { file: "ageofwar.html", title: "Age of War" },
  { file: "ageofwar2.html", title: "Age of War 2" },
  { file: "agesofconflict.html", title: "Ages of Conflict" },
  { file: "amongus.html", title: "Among Us" },
  { file: "angrybirds.html", title: "Angry Birds" },
  { file: "angrybirdsshowdown.html", title: "Angry Birds Showdown" },
  { file: "angrybirdsspace.html", title: "Angry Birds Space" },
  { file: "awesometanks.html", title: "Awesome Tanks" },
  { file: "awesometanks2.html", title: "Awesome Tanks 2" },
  { file: "backrooms.html", title: "Backrooms" },
  { file: "baconmaydie.html", title: "Bacon May Die" },
  { file: "badicecream.html", title: "Bad Ice Cream" },
  { file: "badicecream2.html", title: "Bad Ice Cream 2" },
  { file: "badicecream3.html", title: "Bad Ice Cream 3" },
  { file: "badparenting.html", title: "Bad Parenting" },
  { file: "badpiggies.html", title: "Bad Piggies" },
  { file: "baldisbasics.html", title: "Baldi's Basics" },
  { file: "baseballbros.html", title: "Baseball Bros" },
  { file: "basketballlegends.html", title: "Basketball Legends" },
  { file: "basketballstars.html", title: "Basketball Stars" },
  { file: "basketbros.html", title: "Basket Bros" },
  { file: "basketrandom.html", title: "Basket Random" },
  { file: "bitlife.html", title: "BitLife" },
  { file: "bitplanes.htm", title: "Bitplanes" },
  { file: "blockysnakes.html", title: "Blocky Snakes" },
  { file: "bloonsTD.html", title: "Bloons TD" },
  { file: "bloonsTD2.html", title: "Bloons TD 2" },
  { file: "bloonsTD3.html", title: "Bloons TD 3" },
  { file: "bloonsTD4.html", title: "Bloons TD 4" },
  { file: "bloonsTD5.html", title: "Bloons TD 5" },
  { file: "bloxorz.html", title: "Bloxorz" },
  { file: "blumgiracers.html", title: "Blumgi Racers" },
  { file: "blumgirocket.html", title: "Blumgi Rocket" },
  { file: "bobtherobber.html", title: "Bob the Robber" },
  { file: "bobtherobber2.html", title: "Bob the Robber 2" },
  { file: "bobtherobber5.html", title: "Bob the Robber 5" },
  { file: "bouncymotors.html", title: "Bouncy Motors" },
  { file: "bowmasters.html", title: "Bowmasters" },
  { file: "boxingrandom.htm", title: "Boxing Random" },
  { file: "breakingthebank.html", title: "Breaking the Bank" },
  { file: "bubbleshooter.html", title: "Bubble Shooter" },
  { file: "candycrush.html", title: "Candy Crush" },
  { file: "capybaraclicker.html", title: "Capybara Clicker" },
  { file: "cardrawing.html", title: "Car Drawing" },
  { file: "carkingarena.html", title: "Car King Arena" },
  { file: "chess.html", title: "Chess" },
  { file: "choppyorc.html", title: "Choppy Orc" },
  { file: "circloO.html", title: "CircloO" },
  { file: "circloO2.html", title: "CircloO 2" },
  { file: "clashofvikings.html", title: "Clash of Vikings" },
  { file: "cleanupio.html", title: "Cleanup.io" },
  { file: "clusterrush.html", title: "Cluster Rush" },
  { file: "cookieclicker.htm", title: "Cookie Clicker" },
  { file: "crazycars.html", title: "Crazy Cars" },
  { file: "crazycattle3D.html", title: "Crazy Cattle 3D" },
  { file: "crazycrashlanding.html", title: "Crazy Crash Landing" },
  { file: "crazymotorcycle.html", title: "Crazy Motorcycle" },
  { file: "crossyroad.htm", title: "Crossy Road" },
  { file: "cuttherope.html", title: "Cut the Rope" },
  { file: "dadish.html", title: "Dadish" },
  { file: "dadish2.html", title: "Dadish 2" },
  { file: "dadish3.html", title: "Dadish 3" },
  { file: "deathchase.html", title: "Death Chase" },
  { file: "deathrun3D.html", title: "Death Run 3D" },
  { file: "demolitionderbycrashracing.html", title: "Demolition Derby Crash Racing" },
  { file: "doodlejump.html", title: "Doodle Jump" },
  { file: "drawclimber.html", title: "Draw Climber" },
  { file: "dreadheadparkour.htm", title: "Dreadhead Parkour" },
  { file: "driftboss.htm", title: "Drift Boss" },
  { file: "drivemad.htm", title: "Drive Mad" },
  { file: "ducklife.html", title: "Duck Life" },
  { file: "ducklife2.html", title: "Duck Life 2" },
  { file: "ducklife3.html", title: "Duck Life 3" },
  { file: "ducklife4.html", title: "Duck Life 4" },
  { file: "ducklife5.html", title: "Duck Life 5" },
  { file: "ducklingsio.html", title: "Ducklings.io" },
  { file: "eagleride.html", title: "Eagle Ride" },
  { file: "earntodie.html", title: "Earn to Die" },
  { file: "earntodie2.html", title: "Earn to Die 2" },
  { file: "eggycar.html", title: "Eggy Car" },
  { file: "elasticface.htm", title: "Elastic Face" },
  { file: "escaperoad.html", title: "Escape Road" },
  { file: "escaperoad2.html", title: "Escape Road 2" },
  { file: "escapingtheprison.html", title: "Escaping the Prison" },
  { file: "evilglitch.html", title: "Evil Glitch" },
  { file: "fancypantsadventure.html", title: "Fancy Pants Adventure" },
  { file: "fancypantsadventure2.html", title: "Fancy Pants Adventure 2" },
  { file: "fireboyandwatergirl.html", title: "Fireboy and Watergirl" },
  { file: "fireboyandwatergirl2.html", title: "Fireboy and Watergirl 2" },
  { file: "fireboyandwatergirl3.html", title: "Fireboy and Watergirl 3" },
  { file: "fireboyandwatergirl4.html", title: "Fireboy and Watergirl 4" },
  { file: "flappybird.html", title: "Flappy Bird" },
  { file: "floodrunner2.html", title: "Flood Runner 2" },
  { file: "floodrunner3.html", title: "Flood Runner 3" },
  { file: "floodrunner4.html", title: "Flood Runner 4" },
  { file: "fnaf.html", title: "FNAF" },
  { file: "fnaf2.html", title: "FNAF 2" }
];
