window.GAME_LIST = [
  { file: "10minutestilldawn.html", title: "10 Minutes till Dawn" },
  { file: "angrybirds.html", title: "Angry Birds" },
  { file: "angrybirdsspace.html", title: "Angry Birds Showdown" },
  { file: "backrooms.html", title: "Backrooms" },
  { file: "badpiggies.html", title: "Bad Piggies" },
  { file: "baldisbasics.html", title: "Baldi's Basics" },
  { file: "basketrandom.html", title: "Basket Random" },
  { file: "bitlife.html", title: "Bitlife" },
  { file: "bowmasters.html", title: "Bowmasters" },
  { file: "chess.html", title: "Chess" },
  { file: "1.12.html", title: "1.12" },
  { file: "1v1.lol.html", title: "1v1.lol" },
  { file: "3Dflightsimulator.html", title: "3D Flight Sim" },
  { file: "8ballclassic.html", title: "8 Ball" },
  { file: "amongus.html", title: "Among us" },
  { file: "drifthunters.htm", title: "Drift Hunters" },
  { file: "cookieclicker.html", title: "Cookie Clicker" },
];
